### ISSUE TITLE
missing rule for ghacks.net

### ISSUE THREAD

**Issue by basings** [mozilla/cookie-banner-rules-list#283]
https://www.ghacks.net

**Comment by Trikolon** [comment]
That's a Didomi CMP banner which we actually have a rule for. But it only works in service mode 2 where we can do a fall-back to accept all. We're not shipping this fallback mechanism due to privacy concerns. We can't take the reject-all option since the banner on GHacks doesn't have a reject-all button:

![image](https://github.com/mozilla/cookie-banner-rules-list/assets/1077860/caed2c3c-4ed1-4a53-af61-f16673834ee0)
