### ISSUE TITLE
Add a rule for androidpolice.com (depending on Admiral)

### ISSUE THREAD

**Issue by saschanaz** [mozilla/cookie-banner-rules-list#284]

**Comment by saschanaz** [comment]
I see no stable way to select the buttons 🤔

And amusingly, the site considers the Reject button very seriously and does not write anything to the cookie to remember it's rejected, so a refresh shows the cookie banner again 🙂

**Comment by saschanaz** [comment]
Maybe you already clicked it? 

![image](https://github.com/mozilla/cookie-banner-rules-list/assets/3396686/f9e1e4ff-d8c0-4e63-8bef-daf749efc3d0)

**Comment by saschanaz** [comment]
Hmm, my PBM still shows the cookie banner, not sure why it does not on your profile

**Comment by cadeyrn** [comment]
As I see the cookie dialog in a new profile, I tried to write a rule. But during testing the rule I noticed that once you reload the page, you see the dialog again. The same happens in other browsers like Chrome, so it seems that the reject option is kind of broken (well, maybe that's exactly how they want it so that people accept…)

Therefore, I wrote an opt-in rule, but it only works with cookie mode = 2.
