### ISSUE TITLE
www.brigitte.de first try found directly a non working filter

### ISSUE THREAD

**Issue by mgfirewater** [mozilla/cookie-banner-rules-list#285]
i try a german woman magazin, which i never visit before. it fails

www.brigitte.de

**Comment by Trikolon** [comment]
This banner uses sourcepoint (CMP) which we can handle, but only in service mode 2. That's because it only has an opt-in / accept-all option. If you want Firefox to handle these kind of banners you need to change the following prefs:

`cookiebanners.service.mode = 2`
`cookiebanners.service.mode.privateBrowsing = 2` (if you want this to work in private browsing too)
`cookiebanners.service.enableGlobalRules = true` (might need to update this pref too in release builds)
