### ISSUE TITLE
Banner showing on `stackoverflow.com` in service mode 1

### ISSUE THREAD

**Issue by yokoffing** [mozilla/cookie-banner-rules-list#33]
Example: `https://stackoverflow.com/questions/27038732/css-fade-in-out-blinking`

`cookiebanners.service.mode` is `1`

![Screenshot 2022-11-15 at 16-08-06 Css fade-in-out blinking](https://user-images.githubusercontent.com/11689349/202025586-f0de2e89-9879-46df-940c-a62a9f11d53a.png)

**Comment by Trikolon** [comment]
@yokoffing Does Firefox correctly handle the banner if you set the service mode to 2?

**Comment by yokoffing** [comment]
> @yokoffing Does Firefox correctly handle the banner if you set the service mode to 2?

Yes, it works with `2`. But isn't there privacy implications with using `2` over `1`?

**Comment by Trikolon** [comment]
Our implementation only performs a single click, this is to provide a good UX. Handling "customize" menus like shown in the screenshot can lead to long delays preventing users from using the page. Banners can be hidden while they're handled but this is sort of hit-and-miss and can still lead to bad UX or broken sites.

Service mode 2 == `REJECT_OR_ACCEPT` means we reject banners if that's a one-click option, otherwise we fall back to the accept button. Privacy wise that's worse than reject, that's why we have mode 1 where we keep these banners so users can make their own choices. However you still get things like Total Cookie Protection in Firefox/Gecko which make the accept option slightly less problematic, limiting 3rd-party cookie tracking.

I'll close this as wontfix since our mechanism behaves as expected.

**Comment by yokoffing** [comment]
> Service mode 2 == `REJECT_OR_ACCEPT` means we reject banners if that's a one-click option, otherwise we fall back to the accept button. Privacy wise that's worse than reject, that's why we have mode 1 where we keep these banners so users can make their own choices. However you still get things like Total Cookie Protection in Firefox/Gecko which make the accept option slightly less problematic, limiting 3rd-party cookie tracking.

This is helpful. Thank you for the response!
