### ISSUE TITLE
medonet.pl - site breakage - unscrollable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#84]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/17

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) `cookiebanners.service.mode` set to `2`
> 2) Access `https://www.medonet.pl/`
>
> ## Expected Behavior
> scrollable
>
> ## Actual Behavior
> unscrollable
> 
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/2da392c7-8668-4245-bc0a-7b6ab6fd212a.png)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/2da392c7-8668-4245-bc0a-7b6ab6fd212a.png)

**Comment by hokonch** [comment]
@cboozar 

I have reported 11 similar issues and most are still 100% reproducible in my environment.
The exceptions are https://github.com/mozilla/cookie-banner-rules-list/issues/86 and https://github.com/mozilla/cookie-banner-rules-list/issues/87.
I failed to reproduce twice in 10 attempts for https://github.com/mozilla/cookie-banner-rules-list/issues/86, and could not reproduce anymore for https://github.com/mozilla/cookie-banner-rules-list/issues/87, which I recall was not highly reproducible even when I reported it.
In both cases, as with your test, instead of the site being unscrollable, the cookie banner does not disappear at all.

**Comment by artines1** [comment]
I briefly looked into the issue here. It's a timing issue that we click the button too soon, so some data required to finish the clicking hasn't been ready yet.

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.3 release on RS prod.
